definitions:
  models.MonthlyCategoryGroup:
    properties:
      categories:
        items:
          $ref: '#/definitions/models.MonthlyCategoryItem'
        type: array
      month:
        type: string
    type: object
  models.MonthlyCategoryItem:
    properties:
      category2:
        type: string
      total:
        type: number
    type: object
  models.ResponseWithMonths:
    properties:
      months:
        items:
          $ref: '#/definitions/models.MonthlyCategoryGroup'
        type: array
    type: object
  models.Transaction:
    properties:
      amount:
        example: 15000
        type: number
      categories:
        example:
        - '["makanan"'
        - '"jajan"]'
        items:
          type: string
        type: array
      categories_view:
        description: View-only field for Swagger or API response
        items:
          type: string
        type: array
      category:
        example: makanan
        type: string
      created_at:
        example: "2025-08-07T12:00:00Z"
        type: string
      description:
        example: Beli Mie Gacoan
        type: string
      id:
        example: 1
        type: integer
      transaction_at:
        example: "2025-08-07T12:00:00Z"
        type: string
      type:
        example: pengeluaran
        type: string
    type: object
  models.TransactionResponse:
    properties:
      amount:
        type: number
      category:
        type: string
      created_at:
        description: string untuk tampil WIB
        type: string
      description:
        type: string
      id:
        type: integer
      transaction_at:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/dashboard:
    get:
      description: Menampilkan ringkasan transaksi
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Dashboard utama
      tags:
      - Dashboard
  /api/dashboard/bar:
    get:
      description: Menampilkan grafik batang pengeluaran per kategori
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: Grafik batang pengeluaran
      tags:
      - Dashboard
  /api/dashboard/donut:
    get:
      description: Menampilkan grafik donat pemasukan per kategori
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: Grafik donat pemasukan
      tags:
      - Dashboard
  /api/dashboard/monthly-bar:
    get:
      description: Menampilkan pengeluaran per kategori tiap bulan (maksimal 3 bulan
        terakhir)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithMonths'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Statistik pengeluaran 3 bulan terakhir
      tags:
      - Statistik
  /api/transactions:
    get:
      description: Menampilkan semua transaksi dengan filter dan pagination
      parameters:
      - description: Page number (default 1)
        in: query
        name: page
        type: integer
      - description: Limit per page (default 10)
        in: query
        name: limit
        type: integer
      - description: Filter by type (pemasukan/pengeluaran)
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TransactionResponse'
            type: array
      summary: Ambil daftar transaksi
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      description: Menambahkan data transaksi
      parameters:
      - description: Transaksi baru
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/models.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
      summary: Tambah transaksi baru
      tags:
      - Transactions
  /api/transactions/{id}:
    delete:
      description: Menghapus transaksi berdasarkan ID
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hapus transaksi
      tags:
      - Transactions
  /api/transactions/top5:
    get:
      consumes:
      - application/json
      description: Mendapatkan 5 transaksi terbaru berdasarkan tanggal dibuat (created_at
        DESC).
      produces:
      - application/json
      responses:
        "200":
          description: Daftar 5 transaksi terbaru
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/models.TransactionResponse'
              type: array
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get top 5 latest transactions
      tags:
      - Transactions
swagger: "2.0"
